# Run temporal.io dev server
networks:
  temporal:
    driver: bridge
services:
  temporal:
    image: temporalio/server:latest
    networks:
      - temporal
    ports:
      - "8233:8233"
      - "7233:7233"

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    depends_on:
      - temporal
    networks:
      - temporal

  gateway:
    build:
      dockerfile: gateway.Dockerfile
      context: .
    ports:
      - "8091:8091"
    depends_on:
      - temporal
    networks:
      - temporal
